from .core import ClassificationPipe
from .object_detection_pipeline import ObjectDetectionPipe
from .semantic_segmentation_pipeline import SemanticSegPipe
from .instance_segmentation_pipeline import InstanceSegPipe
